In [22]:
import numpy as np
from sklearn.decomposition import PCA

# 1. Create a sample dataset
data = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

# 2. Standardize the data (important for PCA)
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
data_scaled = scaler.fit_transform(data)

# 3. Create a PCA object with desired number of components
pca = PCA(n_components=2)  # Reduce to 2 dimensions

# 4. Fit the PCA model to the data
pca.fit(data_scaled)

# 5. Transform the data onto the principal components
data_pca = pca.transform(data_scaled)

print("Original data:")
print(data)
print("_______________________________________")

# 6. Access principal components (eigenvectors) and explained variance
print("Principal components:")
print(pca.components_)
print()
print("Explained variance:")
print(pca.explained_variance_ratio_)
print()

# 7. Print the transformed data
print("Transformed data:")
print(data_pca)

Original data:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
_______________________________________
Principal components:
[[-0.57735027 -0.57735027 -0.57735027]
 [-0.81649658  0.40824829  0.40824829]]

Explained variance:
[1.00000000e+00 1.11294118e-34]

Transformed data:
[[ 2.12132034e+00  4.46551999e-16]
 [ 0.00000000e+00  0.00000000e+00]
 [-2.12132034e+00 -4.46551999e-16]]
